### ISSUE TITLE
Do you have the shell commands?

### ISSUE THREAD

**Issue by Dracoy** [bruhautomation/BRUH2-Home-Assistant-Configuration#2]
In these scripts you refer to different shell commands. Do you mind sharing these as well?

https://github.com/brusc/Home-Assistant-Configuration/blob/master/shell_commands.yaml

I'm trying to figure out two things currently.

1) How you do a device refresh manually for owntracks - I think I should be able to figure it out in your script.
2) How to send any media to one of the media players. I think it is through one of your shell commands. Thanks!

**Comment by brusc** [comment]
Sure thing! Just posted them now. 

To manually refresh Owntracks you need to check the box to enable remote commands in the Owntracks app. Then, just post a message like this `{"_type":"cmd","action":"reportLocation"}` to the same topic that your Owntrack's device reports on.

This shell command utilizes mosquito to post that message to the topic as shown.  

mosquitto_pub -d -u USERNAME -P PASSWORD -t owntracks/homeassistant/ben6p/cmd -m "{"_type":"cmd","action":"reportLocation"}"

I'm still working on finding robust ways to trigger media. My setup keeps changing before I can optimize the setup. The scripts I have work okay for calling a specific file in Kodi, but it isn't robust enough to be terribly useful. I need to explore more options soon. Cheers!

**Comment by Dracoy** [comment]
Thanks! Your configuration has been really helpful. I'll play around with it a bit more. I noticed you asked a while ago on how to send music to chromecast. Did you every figure this out? Your lullaby automation seems to suggest the cast but I can't seem to get it working.

> ```
> - alias: Start Music
>   trigger:
>     platform: state
>     entity_id: input_select.music_test
>     to: "Start"
>   action:
>     service: media_player.play_media
>     data:
>       entity_id: media_player.audiounlimited
>       media_id: http://dracoy.com/wp-content/uploads/2016/05/eye.mp3
>       media_type: audio/mp4
> ```

**Comment by brusc** [comment]
Oi, totally forgot about that. Yeah, I was playing with that for a while. The short answer is no - it doesn't work anymore. It used to, but pychromecast broke at some point because of a Chromecast update. I thought some people had fixed this and were able to initiate media on the Chromecast, but I haven't tested it in a while.  I'm coming back to this soon though and I'll let you know if find a good solution.
