### ISSUE TITLE
How to show the last updated time for all the states?

### ISSUE THREAD

**Issue by sriramsv** [bruhautomation/BRUH2-Home-Assistant-Configuration#3]
Hi, I came across your config and the gif shows that the states have the last updated time.

Can you let me know ?

**Comment by mcfrojd** [comment]
Im really interested in this to. I have been going thru your files but i cant seem to find out how you do it.

**Comment by snarby2013** [comment]
And me! Ive seen this in a few examples and really cant figure it out. I also don't have a list of available states on the right of the screen in Home Assistant like Ive seen in some of your videos, any ideas? cheers!

**Comment by Joeboyc2** [comment]
Hi All,

I believe these are depreciated features and are no longer available in the newest releases

**Comment by bruhautomation** [comment]
Correct! Yeah, sadly, this is a deprecated feature to streamline the UI. My apologies for not responding sooner!

**Comment by thundergreen** [comment]
Just today I was thinking about this.  Would like having exactly this
feature again.  Was it removed because of reliability  or what was the
reason?

Am 10.01.2017 22:11 schrieb "BRUH Automation" <notifications@github.com>:

**Comment by bruhautomation** [comment]
My understanding is that it was taken away to streamline the UI and make it more compliant with Google's material design UI guidelines. It may also have been the result of some core changes, but I'm not sure. Sadly, I don't think there is a way to easily bring this back. You could look through GitHub though and see if you can track down the code changes that removed the time stamp. You could undo that on your local instance of HA.
